/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "protobuf/metadata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AudioFile, AudioFile, AUTO)


PB_BIND(Restriction, Restriction, AUTO)


PB_BIND(Image, Image, AUTO)


PB_BIND(ImageGroup, ImageGroup, 2)


PB_BIND(Album, Album, 2)


PB_BIND(Artist, Artist, 2)


PB_BIND(Track, Track, 4)


PB_BIND(Episode, Episode, 2)




