/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "protobuf/spirc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TrackRef, TrackRef, 2)


PB_BIND(State, State, 4)


PB_BIND(Capability, Capability, 2)


PB_BIND(DeviceState, DeviceState, 4)


PB_BIND(Frame, Frame, 4)






